### ISSUE TITLE
Allow users to add an app to block

### ISSUE THREAD

**Issue by antlam** [mcomella/NotificationManager#12]
WIP - Basically a full-page dialog of apps the user has installed. @brampitoyo and myself were exploring what subtitle would be more helpful. For the time being, we can just use size of application just like the system UI. 
- FAB -> Choose application (this mock) -> Added to default list

![prev_applist_mock1](https://cloud.githubusercontent.com/assets/1994820/18324111/a1029e62-74ef-11e6-8947-f17002c8dd17.png)

**Comment by mcomella** [comment]
Done in one_list branch.
