### ISSUE TITLE
Use empty state to ask for permission and onboard users

### ISSUE THREAD

**Issue by antlam** [mcomella/NotificationManager#15]

**Comment by antlam** [comment]
Had some fun with this but still finishing it up. WIP

![prev_empty_mock1](https://cloud.githubusercontent.com/assets/1994820/18331361/2ca156ac-7513-11e6-92fa-bfecbec43a8d.png)

**Comment by mcomella** [comment]
Completed (with extra permission screen) in one_list branch.

Waiting on antlam for final designs.

**Comment by antlam** [comment]
![screen shot 2016-09-09 at 11 22 54 am](https://cloud.githubusercontent.com/assets/1994820/18398072/e2cef58e-767f-11e6-9bcc-450cafe8bdae.png)

Final designs! As final as a V1 gets anyways :) 

@brampitoyo check it out! thoughts?

**Comment by antlam** [comment]
@mcomella - Added the image resource for the giraffe in Resources folder

**Comment by mcomella** [comment]
All fixed on master.
