### ISSUE TITLE
Single press action disables notifications

### ISSUE THREAD

**Issue by antlam** [mcomella/NotificationManager#3]
After an app is added, a single press should be the interaction for quickly enabling/disabling notifications.

**Comment by antlam** [comment]
To keep things single for V1, we can use system UI switches here. 

![prev_home_mock1](https://cloud.githubusercontent.com/assets/1994820/18328286/04f3e17a-7503-11e6-9a42-00b0962da76d.png)

**Comment by mcomella** [comment]
Done in one_list branch.
